### ISSUE TITLE
Make Genson be OSGi-compliant

### ISSUE THREAD

**Issue by lennartj** [owlike/genson#117]
In the case of Genson, OSGi-compliance does not require any code changes, but only the addition of a single plugin which synthesizes the MANIFEST.MF files within the artifact JARs.

This yields no problem for the genson artifacts/projects but simplifies life drastically for folks attempting to use Genson in an OSGi environment.

**Comment by martin-petzold** [comment]
Should be re-opened because the build does not contain OSGi headers!

**Comment by lennartj** [comment]
Does the felix-maven-plugin execution not fire in the build?

**Comment by martin-petzold** [comment]
I don't know, but the JAR does not have any OSGi headers or any other OSGi related data.
