### ISSUE TITLE
Wrong Error Message on NumberFormatException

### ISSUE THREAD

**Issue by havrikov** [owlike/genson#119]
When parsing an input like `[42e+600]` the error thrown is:  
`java.lang.NumberFormatException: Infinity is not a valid json number.`
Even though the number provided is arguably slightly smaller than infinity ;)

**Comment by EugenCepoi** [comment]
What result would you expect? This number exceeds the max value that can be represented with a double on the JVM. For ex: java.lang.Double.valueOf("42e+600") would return you infinity.

**Comment by havrikov** [comment]
I think an `IllegalArgumentException` would fit better.

**Comment by EugenCepoi** [comment]
In this case the meaning of NumberFormatException is basically that 42e+600 (or Infinity) is not a valid json number. That seems relatively accurate to me especially in the context of a parser (while I'd use IllegalArgEx to signal wrong user input).
