### ISSUE TITLE
Strange behaviour while using sockets

### ISSUE THREAD

**Issue by Vasniktel** [owlike/genson#143]
See [StackOverflow question](https://stackoverflow.com/q/53718743/8728510)

**Comment by EugenCepoi** [comment]
Did you close it because it turned out to not be a problem in Genson?

**Comment by Vasniktel** [comment]
Yes. That was my mistake actually. I've forgotten that socket streams are always opened so server will be listening to it forever unless you specify some protocol to denote the size of a query.

**Comment by Vasniktel** [comment]
Nevertheless, it is still very interesting situation. The question arises: why all those test cases (with constants and 0..9 range) are so? (E. g. gson just stalls in any case).

**Comment by EugenCepoi** [comment]
Some code paths in the reading API will try to eagerly ensure that there are at least N bytes available or EOF has been reached. This happens all the time when parsing a number (that is not a constant) as you noted.

An option could be to implement a small layer that serializes to a byte array or string, gets the message length and writes it to the output, followed by the payload. On the reading side you would first read the length and then read from the stream in a while loop until you reached that length or EOF.

Then you would just pass to Genson.deseralize this in memory message.
