### ISSUE TITLE
JSR-353 compliance issue

### ISSUE THREAD

**Issue by salyh** [owlike/genson#36]
Genson is missing RFC 4627 charset detection which is required by JSR-353 

See API description of "JsonParserFactory.createParser(InputStream in)"
https://json-processing-spec.java.net/nonav/releases/1.0/pfd-draft/javadocs/javax/json/stream/JsonParserFactory.html#createParser(java.io.InputStream)

**Comment by EugenCepoi** [comment]
Thanks @salyh for reporting it. 

Initially it was intentionally left out in order to have more time to implement other features (that I considered more important/widely needed) and forgot to add it later.
