### ISSUE TITLE
GWT support?

### ISSUE THREAD

**Issue by xamde** [owlike/genson#44]
I am always looking for nice libs to use on the server and client side with GWT. GWT simply means, don't use classes on the client side that contain unsupported JRE parts. The list is here: http://www.gwtproject.org/doc/latest/RefJreEmulation.html e.g. there a no streams/writers/readers. The client side would also need JSON creation and reading, I guess.

**Comment by EugenCepoi** [comment]
Hum, I am not sure to understand what you are suggesting?
Even outside of the io classes, genson does a lot of introspection/reflection and I guess that some of that stuff is maybe not available too. If you want to see Genson rewritten to use only classes available on GWT client side, I guess the answer is no :) Too much work, for a very specific technology, only people using GWT would benefit from it and no one else.

But I think you can still use Genson on server side, without trying to use it on client side.

**Comment by xamde** [comment]
I see. Yes, GWT doesn't allow reflection at all. I completely agree to your points.

**Comment by EugenCepoi** [comment]
However if you want to provide some converters for GWT specific types, it is welcome. You can do it by creating a new Bundle for GWT. :)
