### ISSUE TITLE
Genson annotations not overriding Jaxb annotations

### ISSUE THREAD

**Issue by jessecrossley** [owlike/genson#45]
I have a Jersey no-xml webapp that includes the GensonJsonConverter automatically.  My generated, annotated JAXB pojos receive @JsonIgnore annotations on certain fields (I did not add the annotations to the accessors or mutators), but the ignore is ignored.  For example, I have a createdBy field annotated thusly:
    @XmlElement(name = "CreatedBy", required = true)
    @JsonIgnore
    protected String createdBy;

Does this ring any bells?  I've attempted to make my own Genson ContextResolver and control the GensonBuilder, but it did not suffice (it's more than possible that I didn't correctly configure the builder).  Looking through the JAXBBundle code, it isn't readily apparent to me how it falls back to the @JsonIgnore annotations.

**Comment by EugenCepoi** [comment]
By default Genson favors get/set over field access (and if the field is private or protected, it is not being used). In your case I think Genson will pick the getCreatedBy method and use its annotations. 

I did made a choice (that appears to be not so good now) of separating annotations from fields, get and set, in order to allow more granular configuration. I will have a look into providing a way to "merge" the annotations from field/get/set. Still I hesitate with merging only annotations between methods or also from fields.

The easy solution in your case would be to configure Genson to use only fields, this way it does not even consider the methods and it would work directly.

Please try this configuration:

```java
Genson genson = new GensonBuilder()
  .useFields(true, VisibilityFilter.PRIVATE) // use only fields with any visibility
  .useMethods(false)
  .withBundle(new JAXBBundle()) // if you want to enable jaxb annotations
  .create();
```

Note that instead you can also use @XmlAccessorType(XmlAccessType.FIELD) annotation on your class in order to use only fields and no java bean properties. However this will be used by all libs you use that impl. JAXB spec.

Does one of those solution answer to your problem or each has a disadvantage in your use case?

**Comment by jessecrossley** [comment]
Since my JAXB beans are used as JPA beans, I want to avoid adding the @XmlAccessorType annotation to the generated classes.

I have attempted to use the GensonBuilder to configure Genson directly (and logging does indicate that my GensonContextResolver is used to access the GensonJsonConverter), but the configuration seems to be ignored.  

In fact, after adding extensive logging to Genson, I see that with my GensonContextResolver, the GensonBuilder.create() method is called twice on the same thread (both calls trace through a great deal of Jersey introspection and don't seem to respect any efforts to synchronize in order to produce just a single Genson instance).  When I remove my GensonContextResolver and allow  the JerseyAutoDiscoverable to initialize Jersey, then I see create called 3 times!  Interestingly, the first two are the same as in my bad scenario, while the final create correctly utilizes GensonJsonConverter's GensonStandardResolver.

So the first part of my problem seems to be the multiple calls to GensonBuilder.create() in Jersey.  I've created a test harness to isolate the issue, but I need to simplify the data model before I can share it.  I will add more findings tomorrow.

**Comment by EugenCepoi** [comment]
Hum, I wonder if Jersey is not creating multiple instances of GensonJsonConverter...
If you create your app in Java maybe you can try to instanciate and register your self GensonJsonConverter and pass him your resolver.

**Comment by jessecrossley** [comment]
The multiple-GensonBuilder/Genson instantiation issue not withstanding, I think I've found a symptom of the problem if not the problem itself.  The Genson instance actually called upon to write out the beans does have a CompositeResolver that contains a JaxbAnnotationsResolver, a GensonAnnotationsResolver, and a StandardMutaAccessorResolver.  However, since that is the order they're iterated over, the CompositeResolver is always going with the JaxbAnnotationsResolver and ignoring the others.  Perhaps if I manage to ensure that the GensonAnnotationsResolver goes first...

**Comment by jessecrossley** [comment]
I have a fix! Let's see if you concur...
We can discount the multiple-instances-in-jersey issue, that's a red herring.  The real secret sauce lies in the CompositeResolver and how it orders the default BeanMutatorAccessorResolvers it's constructed with and any BeanMutatorAccessorResolvers that are added later on.  The current `CompositeResolver.add(BeanMutatorAccessorResolver... resolvers)` calls `components.addAll(0, Arrays.asList(resolvers));`.  I modified the method to insert any added resolvers ahead of the last pre-existing resolver.  Since a CompositeResolver is constructed with a GensonAnnotationResolver and StandardMutaAccessorResolver, it seems logical to insert any other Resolvers between them, as that should ensure that Genson annotations are always processed first, then our added JaxbAnnotationsResolver, and finally the standard resolver remains as a default.  The modified method follows:
    public CompositeResolver add(BeanMutatorAccessorResolver... resolvers) {
      components.addAll(components.size() > 0 ? components.size()-1 : 0, Arrays.asList(resolvers));
      return this;
    }

However, this change broke the `FilteringAndRenamingTest..testIncludeProperty()` and I don't immediately know why.  I am interested in why, but I cannot investigate at the moment as I must press on with a separate JAXB-JPA-Genson issue on XmlJavaTypeAdapter/Calendar handling (which I'll report momentarily).

**Comment by EugenCepoi** [comment]
I've made an attempt with the commit above to fix this issue. From now on, bundles are supposed to be registered first, before any other config. 
This way first the bundles register their components and then the users provide/override with their config.
 
I am adding by hand a property name resolver and muta...resolver in the JaxbBundle just before their jaxb alternatives. I think that it might be best this way, as we can not assume how bundles would interact with core genson components. The only place where we know it, is in the bundle it self.

Please see if it fixes your problem. Any comments on the fix are welcome.

Thanks!

**Comment by jessecrossley** [comment]
This fix works for me and is much less hack-y than mine.  Thanks for looking at it.
