### ISSUE TITLE
NPE in ASMCreatorParameterNameResolver

### ISSUE THREAD

**Issue by SimenRokaas** [owlike/genson#53]
We have a case where Genson cannot serialize a validation annotation.

When Genson gets into ASMCreatorParameterNameResolver.read(class) the getResourceAsStream call returns null (maybe because the class of 'ofClass' is an on-the-fly Proxy). The inputstream 'is' then becomes null, which makes 'new ClassReader(is)' fail. We get into the finally clause, which is this:

      try {
        is.close();
      } catch (IOException e) {
      }

This of course throws an uncaught NPE upwards through the callstack.

**Comment by EugenCepoi** [comment]
Thanks for reporting this!
Would fixing it by just checking if it is not null suffice in your case?
Yes I think that you are right, the problem is that it can not find the class because it is a dynamic proxy.

Do you mind making a PR with a fix for it? That would be great :)

Thanks
