### ISSUE TITLE
Quotes & slashes aren't escaped in keys

### ISSUE THREAD

**Issue by alexott** [owlike/genson#62]
Just found a bug in Genson 1.3 that arise when I serialize a map where key string contains a quote or slash character. Here is the minimal test case (full text is in the https://gist.github.com/alexott/c43a43851b08180d8909):

        Map<String, String> m = new HashMap<String,String>();
        m.put("abcde", "normal");
        m.put("fg\"hi", "with quote");
        m.put("ij\\klmn", "with slash");

When I execute it, it generates:

     {"abcde":"normal","fg"hi":"with quote","ij\klmn":"with slash"}

instead of correct (generated with `jackson-core`):

     {"fg\"hi":"with quote","abcde":"normal","ij\\klmn":"with slash"}

I haven't tested with other characters that should be escaped, but this maybe applicable for them as well

**Comment by EugenCepoi** [comment]
Yes you are right. Actually it was on purpose as I thought this should be avoided (most languages don't support such names for attributes/methods). But indeed the spec doesn't forbid those.

Do you have a use case with such keys? If yes I can add it without too much pain. Basically I'd only had to add a kind of cache mapping raw keys to escaped keys, to avoid reescape it every time.

**Comment by alexott** [comment]
I have a code that extracts meta information from HTML pages and stores as JSON, so keys comes directly from pages, without control from my side.  I believe that this happens not very often, but still happens from time to time.

**Comment by EugenCepoi** [comment]
Ah we can't think of every use case :)
I'll try to provide a fix for the next release. But if you need it to work urgently you can hack around by modifying a fork:

- [Remove beforeValue](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L402)
- Add beforeValue [there](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L397) and [there](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L126)
- And replace [all that](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L180-L188) with a call to writeInternalString(_name)

If you would like to contribute code, then you could look into adding a cache of escaped keys (used only for the keys) and run the benchmarks for it, the current version and the one described above. To see which one performs best and make a PR. Thats basically what I was planning to do :)

**Comment by alexott** [comment]
Thanks for hint, but I can't promise that I have time before weekend to do this

**Comment by EugenCepoi** [comment]
@alexott Fixed with the above PR. Will be part of the next release.

**Comment by alexott** [comment]
Thank you very much Eugen!

On Saturday, September 12, 2015, Eugen Cepoi <notifications@github.com>
wrote:

> Closed #62 <https://github.com/owlike/genson/issues/62> via eee7486
> <https://github.com/owlike/genson/commit/eee7486cf4a8abdc7e2db29d914b0e588fc0af65>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owlike/genson/issues/62#event-407917195>.
>


-- 
With best wishes,                    Alex Ott
http://alexott.net/
Twitter: alexott_en (English), alexott (Russian)
Skype: alex.ott
