### ISSUE TITLE
is genson supporting jsonapi.org?

### ISSUE THREAD

**Issue by Salaboy** [owlike/genson#70]
I didn't find anything about it in the documentation, so I'm creating the issue to see if it is really supported

**Comment by EugenCepoi** [comment]
It depends what you mean by does it support. Genson is a databinding and streaming library. If what you want is use Genson to serialize a Pojo using jsonapi format, then no it is not supported out of the box. But actually Genson can be a building block to create such a system.
If you are interested in contributing such a feature, it is highly welcome :)
