### ISSUE TITLE
Pass Classloader in ScalaBeanPropertyFactory

### ISSUE THREAD

**Issue by Rovak** [owlike/genson#71]
When using `Genson` in combination with `Play Framework` i run into `class not found` errors when using development mode. When deserializing JSON to a case class it is unable to find the class.

I was able to solve this problem by extending the `ScalaBeanPropertyFactory` class and pass the Play classloader to the factory so the classloader on [this line](https://github.com/owlike/genson/blob/ebfad72b0033a684f04e2b19cb049d1ced1716b8/genson-scala/src/main/scala/com/owlike/genson/ScalaBeanPropertyFactory.scala#L16) was overridden.

Does it make sense to add an extra constructor to `ScalaBeanPropertyFactory` in which i can pass my own classloader? If so then i will create a PR.

**Comment by EugenCepoi** [comment]
Huh so it doesn't work by default with play dev mode? I guess they do some magic to enable hot classloading. Your fix makes sense. But maybe it would be better to add an option to GensonBuilder allowing to define a custom classloader that would be used elsewhere by Genson. Then [here](https://github.com/owlike/genson/blob/ebfad72b0033a684f04e2b19cb049d1ced1716b8/genson-scala/src/main/scala/com/owlike/genson/ScalaBundle.scala#L21) pass it to the property factory. What do you think?
And yes a PR is very welcome :)

BTW if you see another better option that would make it work by default, it is welcome too :)
Thanks!

**Comment by Rovak** [comment]
It works in play dev mode for the simple cases, i narrowed the error down to the following, this works:

```scala
case class Person(name: String)

val person = genson.fromJson[Person]("{\"name\":\"John Doe\"}")
```

When the case class references another class then it will thrown an error that the class `Person` was not found:

```scala
case class Person(name: String)
case class PhoneBook(persons: List[Person])

val phonebook = genson.fromJson[PhoneBook]("{\"persons\":[]}")
```

**Comment by EugenCepoi** [comment]
Huh that is strange...I wonder why this happens. Not sure I can help much on that as I have no exp. at all with play. Anyway your fix is welcome.

**Comment by Rovak** [comment]
Created a new pull request #72, i haven't thoroughly tested it so it's not ready to merge yet.
