### ISSUE TITLE
Doubles with value of Infinity not handled need setting.

### ISSUE THREAD

**Issue by ericalbers** [owlike/genson#75]
When converting numbers with the value Infinity, it throws an exception,  while this is technically correct, it would be nice to have a flag like the google.gson which has serializeSpecialFloatingPointValues() which when turned on will serialize Infinity as Infinity in the JSON.

**Comment by EugenCepoi** [comment]
Indeed. Then it should be serialized as a json string ("Infinity", "NaN").
The reading side would work without doing anything, except that the ValueType would be string and not number.

Would you like to contribute it? I can show you what code needs to be modified etc.

**Comment by EugenCepoi** [comment]
Basically it would consist in 
- Defining that option in GensonBuilder, Genson and JsonWriter. Update the methods that create a JsonWriter to pass this value
- Move the code from those [checkValidJsonDouble/Float](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L351-L356) to the methods where they are used, like [here](https://github.com/owlike/genson/blob/master/genson/src/main/java/com/owlike/genson/stream/JsonWriter.java#L244). There you could just have a cascade of some if else to handle the different cases properly, and call writeUnsafeValue("+/-Infinity"/"NaN") when the option to serialize them is enabled.
- Write some tests in [JsonWriterTest](https://github.com/owlike/genson/blob/master/genson/src/test/java/com/owlike/genson/stream/JsonWriterTest.java).
