### ISSUE TITLE
Replace usePermissiveParsing with independent configuration options

### ISSUE THREAD

**Issue by EugenCepoi** [owlike/genson#78]
It is better to have a separate config for the features we want to enable/disable.
UsePermissiveParsing should be removed. A new option would be added acceptSingleValueAsList and Genson would by default accept to parse root values not wrapped in an array.

**Comment by EugenCepoi** [comment]
@jiechu please signal it if there are some other options you find unclear or think they should be renamed.

**Comment by jiechu** [comment]
Great solution!
