### ISSUE TITLE
`Option` type parses to `null` instead of `None`

### ISSUE THREAD

**Issue by samthebest** [owlike/genson#82]
Would be the best json lib by far otherwise ... shame

```
scala> import com.owlike.genson.defaultGenson._
import com.owlike.genson.defaultGenson._

scala> case class A(optional: Option[Int])
defined class A

scala> fromJson[A]("{}")
res0: A = A(null)
```

**Comment by EugenCepoi** [comment]
You mean "sad it doesn't support this feature" or "shame that lib sucks"? :p

The handling of missing values in case of an Option is in general a bit of a debate. The argument in favor of not setting some default value (None/whatever) is that this allows people to have default values in their code in case of mutable datastructures. However this is not true for constructor arguments as we need to pass a value which will be null in this case.

I think this could be implemented by adding some new mechanism say InstanceProvider[T] which could be registered by end users to provide custom instances or default instances for missing values for that specific type. By default things would work like now and the handling of missing values would be a config to enable.

I will try to provide this for the up coming release. 
Except if you want to contribute it, in which case I would gladly guide you through Gensons code so you can do it?

**Comment by samthebest** [comment]
I did clone it and have a look, in the hope it would be a one line change somewhere from `null` to `None`, but I realised it's a little more involved.

The behaviour of other libraries, like arganout or spray does indeed default to None when the case class uses `Option` - this is what the user is implying when they put `Option` after all.

Of course, I still think this is amazing how this lib is the only one that doesn't require epic boiler plate, please let's keep it that way if possible.

If it's a debate, then perhaps `fromJson` uses `None` and `fromJsonNullDefault` uses `null` ? Or visa versa, I don't mind, as long as it's still one magic method call.

**Comment by EugenCepoi** [comment]
Yeah it should be a one liner, just a matter of having the new config enabled, but to have it this it requires of course a bit more code.
Thanks for pointing this out, was waiting for someone to ask for it before implementing that feature.

**Comment by EugenCepoi** [comment]
I implemented this new feature. So this is used only for constructor parameters. This means that if you have a mutable pojo/poso which has a property of type Option and the value is missing in the incoming json, then it will remain null. Does it sound good to you? Please feel free to give a shot to the master version.

**Comment by samthebest** [comment]
@EugenCepoi  awesome! Thanks! Which dependency is it? Have you done a release to maven?

Happy to be a "tester" :)

**Comment by EugenCepoi** [comment]
No not yet, you should be able to checkout the master branch and install it locally with mvn install (there are no prerequisites to do build it).

**Comment by EugenCepoi** [comment]
This is now live as part of Genson 1.4 release, if you want to give it a shot.
