### ISSUE TITLE
Genson json converter is active depending on some JAXB annotations

### ISSUE THREAD

**Issue by simdevmon** [owlike/genson#87]
I am using JavaEE 7 with **Payara 4.1.1.161** as an application server and **Genson 1.3** as a maven dependency. 

As far as I understood the documentation, Genson should be active for JAX-RS, once it is in the classpath. I found a strange behavior that depending on some JAXB annotations sometimes Genson json converter is active and sometimes not. 

I created a minimalistic example here:
[TestWebApp.zip](https://github.com/owlike/genson/files/140929/TestWebApp.zip)

I use a simple class **Car**

```
@XmlRootElement
public class Car
{
    // ...
    private String brand;
    private List<Wheel> wheels;
    private Map<String, String> features;

    //@XmlElementWrapper
    //@XmlJavaTypeAdapter(WheelAdapter.class)
    public List<Wheel> getWheels()
    {
        return wheels;
    }

    public void setWheels(List<Wheel> wheels)
    {
        this.wheels = wheels;
    }

    // ...
}
```

and a JAX-RS method:
```
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getCar()
    {
        return Response.ok()
            .entity(
                new Car("BMW", Arrays.asList(new Wheel(17), new Wheel(17), new Wheel(17), new Wheel(17)))
            )
            .build();
    }
```

When the annotations are commented out it looks like JAXB is used:

```
{
  "brand": "BMW",
  "features": {
    "entry": [
      {
        "key": "engine",
        "value": "2.0"
      }
    ]
  },
  "wheels": [
    {
      "size": 17
    },
    {
      "size": 17
    },
    {
      "size": 17
    },
    {
      "size": 17
    }
  ]
}
```

Also when I include only one of the annotations, JAXB is still used. But if I include both of them, it looks like Genson gets active

```
{
  "brand": "BMW",
  "features": {
    "engine": "2.0"
  },
  "wheels": [
    "17 inch",
    "17 inch",
    "17 inch",
    "17 inch"
  ]
}
```

This behavior is strange for me and not predictable. In my opinion Genson should be either active in all cases or not at all. I am not sure if I missed some documentation / configuration, or if it is a bug.

**Comment by EugenCepoi** [comment]
Hi Simon,

What makes you say that Genson is active/inactive? Actually Genson supports
Jaxb annotations, this is enabled by default for JAXRS apps.
So I suspect that all those outputs are generated by Genson.

2016-02-22 8:42 GMT-08:00 Simon <notifications@github.com>:

**Comment by simdevmon** [comment]
Hi Eugen,

as far as I know JAXB without Genson serializes a map to Json like this: 
```"entry": [{"key": "k","value": "v"}]```, 
whereas Genson serializes them to Json key/value pairs directly. 

So my assumption is that Genson is not active, because the map (features) is serialized differently if I change the annotation of another property (wheels), which should not influence the map property at all.

**Comment by EugenCepoi** [comment]
I think you have two competing json ser/de libs in your classpath. I
suspect Payara including moxy and enabling it by default.
At least it is part of their dependencies
https://github.com/payara/Payara/blob/master/appserver/pom.xml#L577-L581
What lib do you want to actually use, Moxy or Genson?
Genson should still process your JAXB annotations even when you remove
@XmlRootElement from your class, maybe moxy isn't which would be an easy
way to disable it.
Otherwise you can try explicitly registering Genson which should override
Moxy. You can do it by implementing the getSingleton method I think and
return an instance of GensonJaxRSFeature or implement getClasses and return
GensonJsonConverter, in your JAXRSConfiguration clasas.

2016-02-22 11:53 GMT-08:00 Simon <notifications@github.com>:

**Comment by simdevmon** [comment]
I want to use Genson only. I tried to remove `@XmlRootElement`, but is has no influence on the behavior. 
I also tried to implement the getSingleton and / or getClasses, but this stopped JAX-RS from working completly and returned only HTTP 404.

```    
    @Override
    public Set<Class<?>> getClasses()
    {
        Set<Class<?>> set = new HashSet<>();
        set.add(GensonJsonConverter.class);
        return set;
    }

   @Override
    public Set<Object> getSingletons()
    {        
        Set<Object> set = new HashSet<>();
        set.add(new GensonJaxRSFeature());
        return set;
    }
```

Did you mean to override the methods this way?

**Comment by EugenCepoi** [comment]
Yes but only one of them not both. Do you have an error when the server starts? Use some break points inside the classes mentioned above to make sure the web server is using them. From there on it should be easier for you to debut what is going on.

**Comment by simdevmon** [comment]
I tested it with 
- no override method 
- only `getClasses()` as an override method
- only `getSingletons()` as an override method 

with a clean Payara 4.1.1.161 installation. The result was always the same as described above. 
I also added a log entry and saw in the server log that the overwritten method was called. There were no errors or warnings in the server log file. 

This is reproducible with the following steps
- Download TestWebApp.zip from above
- Download Payara 4.1.1.161 Full Profile and unzip

on project:
`mvn clean install` 

on cmd:
`asadmin start-domain domain1`
`asadmin deploy --force=true --type war <project-path>\target\TestWebApp.war`
`curl http://localhost:8080/TestWebApp/resources/car`

Result
`{"brand":"BMW","features":{"engine":"2.0"},"wheels":["17 inch","17 inch","17 inch","17 inch"]}`

on project:
Remove `@XmlJavaTypeAdapter(WheelAdapter.class)` on `Car.java`
`mvn clean install` 

`asadmin deploy --force=true --type war <project-path>\target\TestWebApp.war`
`curl http://localhost:8080/TestWebApp/resources/car`

Result:
`{"brand":"BMW","features":{"entry":[{"key":"engine","value":"2.0"}]},"wheels":{"wheels":[{"size":17},{"size":17},{"size":17},{"size":17}]}}`

We changed only something on `getWheels()`, but it influences the `features`
The steps can be repeated with the override methods in place. The behavior is the same. 

I will have a look, if I find some time to get deeper into this issue.

**Comment by EugenCepoi** [comment]
This really looks like a mix with another lib, probably moxy, doing the above steps was supposed to disable it according to moxys doc... I will try to investigate it this weekend.

**Comment by EugenCepoi** [comment]
Huh indeed Moxy seems to override Genson when it shouldn't...even when we tell the container to use Genson it still first picks Moxy and then tries to use Genson (only if Moxy doesn't support something...like the XmlJavaTypeAdapter annotation)?!

Most things that were supposed to disable Moxy didn't work except this one, add this to JAXRSConfiguration class:

```
  @Override
  public Map<String, Object> getProperties() {
    Map<String, Object> props = new HashMap<>();
    props.put("jersey.config.disableMoxyJson", true);

    return props;
  }
```

Let me know on how it goes.

**Comment by simdevmon** [comment]
Thank you for investigating @EugenCepoi. I added the property and it works as expected now.
From my point of view the issue can be closed, however it might be worth to mention this in the documentation or report this to Payara / Moxy if the behavior is not compliant with the spec.
